# Dependencies
markdown:         redcarpet
highlighter:      pygments

# Permalinks
permalink:        pretty

# Setup
title:            sn99's blog
tagline:          'sn99'
description:      'Blog for sn99'
url:              https://sn99.github.io/
baseurl:          https://sn99.github.io/

author:
  name:           'Siddharth Naithani'
  url:            https://twitter.com/SiddharthNait12

paginate:         5

# Custom vars
version:          2.1.0

github:
  repo:           https://github.com/poole/hyde
